pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/cache
postgis:
  image: "osm2vectortiles/postgis"
  volumes_from:
   - pgdata
  ports:
   - "5432"
pgbouncer:
  image: "osm2vectortiles/pgbouncer"
  links:
   - postgis:pg
  ports:
   - "6432"
import-osm:
  image: "osm2vectortiles/import-osm"
  command: ./import-pbf.sh
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
import-osm-diff:
  image: "osm2vectortiles/import-osm"
  command: ./import-diff.sh
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
  environment:
     OSM_UPDATE_BASEURL: "http://download.geofabrik.de/europe/liechtenstein-updates/"
import-labels:
  image: "osm2vectortiles/import-external"
  command: ./import-labels.sh
  links:
  - postgis:db
import-natural-earth:
  image: "osm2vectortiles/import-external"
  command: ./import-natural-earth.sh
  links:
  - postgis:db
import-water:
  image: "osm2vectortiles/import-external"
  command: ./import-water.sh
  links:
  - postgis:db
update-scaleranks:
  image: "osm2vectortiles/update-scaleranks"
  links:
  - postgis:db
detect-dirty-tiles:
  image: "osm2vectortiles/detect-dirty-tiles"
  volumes:
   - ./export:/data/export
  links:
  - postgis:db
enqueue-jobs:
  build: ./tools/enqueue-jobs
  environment:
    AWS_REGION: "eu-central-1"
    TASK_ZOOM_LEVEL: 8
    QUEUE_NAME: "osm2vectortiles_jobs"
export-worker:
  image: "osm2vectortiles/export"
  command: ./export-worker.sh
  volumes:
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
  environment:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_REGION: "eu-central-1"
export:
  image: "osm2vectortiles/export"
  command: ./export-local.sh
  volumes:
   - ./export:/data/export
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
  environment:
    BBOX: "8.4375 46.07323062540838 9.84375 47.040182144806664"
    MIN_ZOOM: "8"
    MAX_ZOOM: "14"
export-list:
  image: "osm2vectortiles/export"
  command: ./export-list.sh
  volumes:
   - ./export:/data/export
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
serve:
  image: "klokantech/tileserver-mapnik"
  volumes:
   - ./export:/data
  ports:
   - "8080:80"
import-sql:
  image: "osm2vectortiles/import-sql"
  links:
   - postgis:db
mapbox-studio:
  image: "osm2vectortiles/mapbox-studio"
  volumes:
   - ./open-streets.tm2source:/projects/open-streets.tm2source
  links:
   - postgis:db
  ports:
   - "3000:3000"
compare-visual:
  image: "osm2vectortiles/compare-visual"
  ports:
   - "4000:3000"
   - "4001:3001"
  links:
   - serve:tileserver
create-extracts:
  image: "osm2vectortiles/create-extracts"
  volumes:
   - ./export:/data/export
  environment:
    S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
    S3_SECRET_KEY: "${S3_SECRET_KEY}"
